### ISSUE TITLE
IntermediateOutputPath not defined by the time nuget.props is imported

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#29]
When the user isn't custom setting the IntermediateOutputPath and relying on the default targets to set it then it is set to late and can't be used in nuget.props.

src/CBT.NuGet/build.props 
``` XML
<CBTNuGetPackagesRestoredMarker
  Condition=" '$(CBTNuGetPackagesRestoredMarker)' == '' ">
    $(IntermediateOutputPath)\$(MSBuildProjectFile).CBTNuGetPackagesRestored
</CBTNuGetPackagesRestoredMarker>
```

Filing issue so it isn't forgotten.
Work around is to disable packagerestore optimization.

**Comment by jeffkl** [comment]
This will also be a problem with the `.props` file written containing a property for each package.  We could disable the optimization if `IntermediateOutputPath` isn't set but we still need to write out the package property file.

The default is set in [Microsoft.Common.CurrentVersion.targets](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L341) and this restoration logic needs to run much earlier so that `.props` files exist before they're imported.

@kingerja what do you think we should do to solve this?

**Comment by kingerja** [comment]
If IntermediateOutputPath is not defined then ...
hmmm some options...
1.  we build it ourselves (probably also saving it as a different property name) using the same rules as the Microsoft.Common.CurrentVersion.targets does and then have a validation target that compares our built path with the real path to ensure we don't get in a wonky state.
2.  Define the path location to some other place like the system tmp or a root obj/.nuget/restoreflag folder.. (we will need to be cautious of projects with the same name colliding with the flagfile name.  Not sure if this will work though.
3.  Do a gross dirty hack of parsing this project with an evaluate only option using the same inputs and use that to set the property up front... (way to fragile and I am only listing this for completeness not because I think it should be considered.)

Looking over these options I would say option 1 would probably be the safest and simplest.  Basically guess but validate.  If we guess wrong the user can always define it to prevent out guessing.  Even if we decided to place it at the baseintermediateoutput path we would need a guess but validate approach unless we just always hardcoded the need to have a folder called obj at the root of the enlistment which would be retarded.  So that basically means we either guess and validate or we put the flag in a well-known folder like the system temp or clutter the source folders (not really an option to clutter the source folder).

**Comment by jeffkl** [comment]
I just remembered that I had to move the declaration of `BaseIntermediateOutputPath` up to Microsoft.Common.props for NuGet functionality in MSBuild 15:

https://github.com/Microsoft/msbuild/commit/862ce619a23877cbfad54fd4acd547ef92f499b3#diff-b9b6ffbc87078d35c66b75cf963b675eR46

We could have the CBT.NuGet module import Microsoft.Common.props (if it hasn't been imported already) and then set `BaseIntermediateOutputPath` to the same defaults in the case that it's an older version of MSBuild.  

The only issue is that the import order could get wacky because modules can have a Before.Microsoft.Common.props and an After.Microsoft.Common.props which would be imported.  So I'm wondering if CBT should import it rather than a module doing it.  Thoughts?

**Comment by jeffkl** [comment]
Nevermind, nothing is going to work except use a different default path if `IntermediateOutputPath` isn't set.  Please see my PR

**Comment by kingerja** [comment]
I took a look it is good.  I merged it over but I don't have the apikey to push the new package to the myget feed.

On Nov 8, 2016 7:46 AM, Jeff Kluge <notifications@github.com> wrote:

Nevermind, nothing is going to work except use a different default path if IntermediateOutputPath isn't set. Please see my PR
