### ISSUE TITLE
what is RestoreDependsOn used for it doesn't show in csproj files pp.txt

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#45]
CBT.Nuget.1.0.0\CBT\Module\After.Microsoft.Common.targets

&lt;PropertyGroup&gt;
    &lt;PrepareForBuildDependsOn Condition=" '$(CBTEnableNuGetPackageRestoreOptimization)' != 'false' "&gt;_CheckForCBTNuGetPackagesRestoredMarker;$(PrepareForBuildDependsOn)&lt;/PrepareForBuildDependsOn&gt;
    &lt;RestoreDependsOn&gt;RestoreNuGetPackages;$(RestoreDependsOn)&lt;/RestoreDependsOn&gt;
  &lt;/PropertyGroup&gt;

filing to look into later

**Comment by josemesona** [comment]
It is defined in the traversal module [here](https://github.com/CommonBuildToolset/CBT.Modules/blob/master/src/CBT.Traversal/CBT/Module/After.Microsoft.Common.targets#L9).  At the time, I figured it only made sense to restore during traversal since restoring a single project is basically built-in.  When we introduce global packages we might need to move this target.

**Comment by kingerja** [comment]
I have wired the globalpackages to the restoredependson property so it should just work now if these modules are installed.    Thanks for the silly question I thought I already did a findstr but I just didn't search the results property or didn't scan the right folder.
